name: "Terraform Apply"
# Cuando Se corre, en este caso cuando hay cambios en terraform
on:
  push:
    branches:
      - main
    paths:  
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  # Credenciales AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 para guardar el estado de terraform
  AWS_REGION: us-east-1

jobs:
  terraform:
    # Donde se va a correr el terraform
    name: "Apply terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    # Descarga el codigo
      - name: Checkout source code 
        uses: actions/checkout@v4
    # Instala terraform

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
    # Pasos terraform init, format, valida, planee e instala

      - name: Terraform init
        id: init
        run: terraform init
    

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
