name: "Terraform Destroy"
# Se corre manual
on:
  workflow_dispatch:

env:
  # Credenciales AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 para guardar el estado de terraform
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-1

jobs:
# Instala terraform, crea un plan y elimina la implementacion
  terraform-destroy:
    name: "Destroy Terraform Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init 

      - name: Terraform plan (destroy)
        id: plan
        run: terraform plan -destroy -no-color -input=false -out destroy-planfile

      - name: Terraform destroy
        run: terraform apply -auto-approve -input=false destroy-planfile
